version: '3'

services:
  postgres:
    container_name: auth_postgres
    image: postgres:16
    restart: no
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/data
      - ./db/pgsql:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
